name: Build Forgejo CLI for ARM64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo install forgejo-cli --root ./dist
      - name: release
        run: |
          VERSION="$(./dist/bin/fj version)"
          gh release create $VERSION --notes "forgejo cli $VERSION"
          gh release upload $VERSION "./dist/bin/fj"
        env:
          GITHUB_TOKEN: ${{ github.token }}