name: Build Forgejo CLI for ARM64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-action@stable
      - run: cargo install fj --locked --root ./dist
      - uses: actions/upload-artifact@v4
        with:
          name: fj-arm64-linux
          path: dist/bin/fj